AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: mail-syncer lambda stack

Parameters:
  DeployEnvironment:
    Type: String
    Default: prod
  ScheduleExpression:
    Type: String
    Default: rate(5 minutes)
  LambdaMemorySize:
    Type: Number
    Default: 512
    MinValue: 128
    MaxValue: 10240
  LambdaTimeoutSeconds:
    Type: Number
    Default: 120
    MinValue: 30
    MaxValue: 900
  LogLevel:
    Type: String
    Default: INFO
  SyncIntervalSeconds:
    Type: Number
    Default: 300
    MinValue: 60
    MaxValue: 86400
  SecretsManagerSecretIds:
    Type: String
    Default: ""

Resources:
  MailSyncerStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "mail-syncer-state-${DeployEnvironment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  MailSyncerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "mail-syncer-${DeployEnvironment}"
      Runtime: python3.11
      Handler: src/lambda_handler.handler
      CodeUri: ../
      Timeout: !Ref LambdaTimeoutSeconds
      MemorySize: !Ref LambdaMemorySize
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          DYNAMODB_TABLE: !Ref MailSyncerStateTable
          LOG_LEVEL: !Ref LogLevel
          SYNC_INTERVAL_SECONDS: !Sub "${SyncIntervalSeconds}"
          AWS_SECRETS_MANAGER_SECRET_IDS: !Ref SecretsManagerSecretIds
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:Query
              Resource: !GetAtt MailSyncerStateTable.Arn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: "*"
      Events:
        ScheduledSync:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Name: !Sub "mail-syncer-schedule-${DeployEnvironment}"
            Enabled: true

Outputs:
  FunctionName:
    Value: !Ref MailSyncerFunction
  FunctionArn:
    Value: !GetAtt MailSyncerFunction.Arn
  StateTableName:
    Value: !Ref MailSyncerStateTable
